### ISSUE TITLE
No Appointments Available

### ISSUE THREAD

**Issue by Jawn78** [SergeyMosin/Appointments#146] opened 2020-10-22 01:23 UTC

**Comment by Jawn78** [comment] 2020-10-22 01:26
The title really says it all. I have another program syncing to a google calendar. I have the calendar synced with my outlook calendar too. But either way, I add the calendar to nextcloud calendar, and I can't use it to select free slots on appointments.  I would really like to use Nextcloud for appointment scheduling, but can't do it without this function.

**Comment by SergeyMosin** [comment] 2020-11-03 12:41
Are there any errors in NC logs or the browser console?

**Comment by SergeyMosin** [comment] 2020-12-05 17:59
Closing due to no activity.

**Comment by nghamilton** [comment] 2020-12-21 23:32
I have a similar issue, and this error is in the logs:

``
Error: Undefined index: more_html at /var/snap/nextcloud/24940/nextcloud/extra-apps/appointments/templates/public/form.php#45/var/snap/nextcloud/24940/nextcloud/extra-apps/appointments/templates/public/form.php - line 45:OC\Log\ErrorHandler::onError(8, "Undefined index: more_html", "/var/snap/n ... p", 45, { file: "/va ... "})/snap/nextcloud/24940/htdocs/lib/private/Template/Base.php - line 178:include("/var/snap/n ... p")/snap/nextcloud/24940/htdocs/lib/private/Template/Base.php - line 150:OC\Template\Base->load("/var/snap/n ... p", { appt_sel_o ... e})/snap/nextcloud/24940/htdocs/lib/private/legacy/OC_Template.php - line 180:OC\Template\Base->fetchPage({ appt_sel_o ... e})/snap/nextcloud/24940/htdocs/lib/public/AppFramework/Http/TemplateResponse.php - line 210:OC_Template->fetchPage({ appt_sel_o ... e})/snap/nextcloud/24940/htdocs/lib/private/AppFramework/Http/Dispatcher.php - line 123:OCP\AppFramework\Http\TemplateResponse->render()/snap/nextcloud/24940/htdocs/lib/private/AppFramework/App.php - line 152:OC\AppFramework\Http\Dispatcher->dispatch(OCA\Appointm ... {}, "formbase")/snap/nextcloud/24940/htdocs/lib/private/Route/Router.php - line 308:OC\AppFramework\App::main("OCA\\Appoin ... r", "formbase", OC\AppFramew ... {}, { action: nu ... "})/snap/nextcloud/24940/htdocs/lib/base.php - line 1008:OC\Route\Router->match("/apps/appointments/form")/snap/nextcloud/24940/htdocs/index.php - line 37:OC::handleRequest()
``

**Comment by SergeyMosin** [comment] 2020-12-22 02:11
@nghamilton 
The ``Error: Undefined index: more_html ...`` is fixed in v1.7.15
However, the error was not the cause of "No Appointments Available", but the "No Appointments Available" caused the error.
Can you check browser console for ``data-state=x`` line.

**Comment by nghamilton** [comment] 2020-12-22 22:08
`data-state:  5` is what the console reports.

**Comment by Jawn78** [comment] 2020-12-23 22:38
@nghamilton  The issue in my case was that you literally need to create appointments and tag them free in the calendar to have them available in the appointment section. A bit counter intuitive to how most availability functions work. Not sure if that's the same problem you have.  I did have to uninstall and reinstall after the upgrade of nextcloud which was a separate issue.

**Comment by SergeyMosin** [comment] 2021-02-24 12:29
Is this still an issue ??

**Comment by inkfs** [comment] 2021-04-21 08:35
I experience the same Issue.
Fresh Nextcloud 21.0.1 install, php 7.4, Appointments 1.9.1 
 I added time-slots to the calendar, I cannot book any. I checked in the "calendar-app" and the time-slot entries are there and tagged as "free".

**Comment by SergeyMosin** [comment] 2021-04-21 11:14
@inkfs can you check browser console (F12) for `data-state`=x line, and if can send me(sergey [at] srgdev.com) the text from the settings dump `Settings > Advanced Settings > Debugging > Settings Dump`

Thanks

**Comment by inkfs** [comment] 2021-04-21 11:38
@SergeyMosin sure, you have new mail.

**Comment by SergeyMosin** [comment] 2021-04-21 15:57
@inkfs 
`data-state:4` means that the page is disabled
`data-state:5` means that appointments are not added (in `simple` mode)

In `Weekly Template` mode what happens if you enable/share the page , any errors in the console ?
![image](https://user-images.githubusercontent.com/10747559/115583779-330ab300-a298-11eb-9484-b0aa0721c368.png)

**Comment by inkfs** [comment] 2021-04-21 18:20
* switched to weekly template mode
* added new weekly timeslot (other timeslots are shown, previously added in simple mode)
* published page with "share online"
-> The newly added timeslot is bookable. Simple mode timeslots are not.

* switch back to simple mode, add new timeslots, publish
-> Newly added simple timeslots are bookable, earlier added timeslots do not appear.

This error appears when clicking on the timeslot reservation (which is enabled) I think it's unrelated:

excludeClickOutsideClasses.js:22 Uncaught TypeError: Cannot read property 'contains' of undefined
    at a.hasNodeOrAnyParentClass (excludeClickOutsideClasses.js:22)
    at a.clickOutsideMiddleware (excludeClickOutsideClasses.js:22)
    at r (v-click-outside.umd.js:1)
    at v-click-outside.umd.js:1

**Comment by danielschubert** [comment] 2021-05-20 08:45
same here, only appointments in the actual week are shown, later slots are shown as not available.
Date Selector does not let me select next week.

**Comment by SergeyMosin** [comment] 2021-05-20 15:28
How many weeks do you have selected in in this drop down :
![image](https://user-images.githubusercontent.com/10747559/119006465-68212880-b95e-11eb-9e1a-8adf5ab22b98.png)

**Comment by danielschubert** [comment] 2021-05-20 19:19
> How many weeks do you have selected in in this drop down :
> ![image](https://user-images.githubusercontent.com/10747559/119006465-68212880-b95e-11eb-9e1a-8adf5ab22b98.png)

Ok, that's it. It took me a while to find THIS dialog, but this was my Problem. 

THX

**Closed** 2021-08-08 17:08 UTC
