### ISSUE TITLE
page not found

### ISSUE THREAD

**Issue by mikweb2017** [SergeyMosin/Appointments#2] opened 2020-02-25 11:46 UTC
I find this app really interesting but I can't publish it online on the logs I can't find anything about it I have nexcloud 18.01 and PHP 7.3

what's wrong with links possibly?

https://cloud.mikweb.eu/index.php/apps/appointments/pub/gZ0vwxm70i%2FcM%2BJ10tE%3D/form

**Comment by small1** [comment] 2020-02-25 17:36
Why did you close this? Did you fix it?

**Comment by mikweb2017** [comment] 2020-02-25 18:17
> Why did you close this? Did you fix it?
I don't know what happened. I didn't do anything, but it works now.

**Comment by SergeyMosin** [comment] 2020-02-25 19:02
Make sure you are using v1.0.4

**Comment by mikweb2017** [comment] 2020-02-26 06:10
i have version 1.0.7  und dont work anymore  Nextcloudd 18.01.  PHP 7.4

https://ac-milan.mikweb.info/nextcloud/index.php/nextcloud/apps/appointments/pub/wfV3YNx39Xwt/form

**Comment by SergeyMosin** [comment] 2020-02-26 16:02
Are you using MySQL or PostgreSQL (could be related to #9 )
Can you do a public share from other apps (publish a Calendar for example)

**Comment by mikweb2017** [comment] 2020-02-26 16:41
> Are you using MySQL or PostgreSQL (could be related to #9 )
> Can you do a public share from other apps (publish a Calendar for example)

i using mysql  yes i can share anything I don't know what happened I have on another domain another instanz of nexcloud with php 7.3 and it works fine

**Comment by mikweb2017** [comment] 2020-02-26 17:00
DATA is  S3 cloud Server but I don't think that's important

**Comment by mikweb2017** [comment] 2020-02-26 19:03
i chek again wiht version 1.0.8  but don t work https://ac-milan.mikweb.info/nextcloud/index.php/nextcloud/apps/appointments/pub/wfV3YNx39Xwt/form

**Comment by SergeyMosin** [comment] 2020-02-26 19:12
This could be some kind of regression from pre v1.0.5 I'll try to reproduce it.
Thanks

**Comment by SergeyMosin** [comment] 2020-02-26 23:50
@mikweb2017 The link below is to the testappt.php file. It will run diagnostic specific to your link. It should print the username of the of link's user on success, otherwise an error message.
Can you run it (php testappt.php) in your Nextcloud install directory - it should have the occ file there.
 
https://gist.github.com/SergeyMosin/8e39e538f2ab3a706bb5d3658edb095f

**Comment by mikweb2017** [comment] 2020-02-27 05:55
> 
> 
> @mikweb2017 The link below is to the testappt.php file. It will run diagnostic specific to your link. It should print the username of the of link's user on success, otherwise an error message.
> Can you run it (php testappt.php) in your Nextcloud install directory - it should have the occ file there.
> 
> https://gist.github.com/SergeyMosin/8e39e538f2ab3a706bb5d3658edb095f

https://ac-milan.mikweb.info/nextcloud/testappt.php

**Comment by mikweb2017** [comment] 2020-02-27 14:57
yes it is

**Comment by SergeyMosin** [comment] 2020-02-27 15:08
Can you try to run this then:
```
php occ app:check-code appointments
```

**Comment by mikweb2017** [comment] 2020-02-27 15:16
App is compliant - awesome job!

**Comment by SergeyMosin** [comment] 2020-02-27 15:35
@mikweb2017 Can you direct email me ( sergey at srgdev.com ) output of the following:
```
php occ config:app:get appointments hk
php occ config:app:get appointments tiv
```
don't post here

**Comment by SergeyMosin** [comment] 2020-02-27 16:13
OK. Looks like the Initialization Vector (tiv) got corrupted somehow. Steps to repair:
1. Disable the app
2. Run this:
```
 php occ config:app:delete appointments tiv
```
3. Enable the app

You should have a new and hopefully working public link

**Comment by mikweb2017** [comment] 2020-02-27 16:19
unfortunately it didn't work out

**Comment by SergeyMosin** [comment] 2020-02-27 16:30
Con you please run this:
```
php -r 'echo extension_loaded("openssl")?"openssl OK\n":"NO openssl\n";'
```

**Comment by mikweb2017** [comment] 2020-02-27 16:59
openssl OK

**Comment by SergeyMosin** [comment] 2020-02-27 17:35
I am really running out of ideas...
Can you post the new public link and the new tiv
```
php occ config:app:get appointments tiv
```

**Comment by mikweb2017** [comment] 2020-02-27 17:52
https://ac-milan.mikweb.info/nextcloud/index.php/nextcloud/apps/appointments/pub/airTDuwiY6sE/form

occ  config:app:get appointments tiv
0fabdec89a8bd11ded0d4b69c28b5ba1

**Comment by mikweb2017** [comment] 2020-02-27 17:57
the only thing different than the 2 instances that I have and here the data is saved on an S3 object 

and the same server with the same configurations

the only thing different than the 2 instances that I have and here the data is saved on an S3 object 


here it works
very strange indeedt works
very strange

**Comment by SergeyMosin** [comment] 2020-02-27 18:11
The token, part between  "pub/" and "/form" in the url does not look right on "ac-milan.mikweb.info"

This is good: **rnGz1mJk3uuX0VY4qrQ%3D** - "cloud.mikweb.eu"
This looks bad: **airTDuwiY6sE** - "ac-milan.mikweb.info"

Let me think.....

**Comment by mikweb2017** [comment] 2020-02-27 18:16
yes right

**Comment by SergeyMosin** [comment] 2020-02-28 03:25
The link below has the PageController.php file with all token related logging enabled. Can you replace the PageController.php in your ... /nextcloud/apps/appointments/lib/Controller/ folder with the provided file. Navigate to the appointments preview page and then to the public page. Then run the following grep command on your nextcloud.log file and send me the output please.
```
 grep "appt_debug:" nextcloud.log
```



https://gist.github.com/SergeyMosin/a16e91debf395c71d5436d25a800617a

**Comment by mikweb2017** [comment] 2020-02-28 06:43
I had to change the configuration nextcloud.log is not readable if configured as S3 object.... here on the link you can download the log

https://ac-milan.mikweb.info/nextcloud/index.php/s/QNGngm89Ex8f3cr

**Comment by SergeyMosin** [comment] 2020-02-28 13:33
The log file you provide spans from 18:22:36 to 18:29:03 and does NOT include any entries related to the appointments app. For the lack of in formation I can not do anything at this point. There are also multiple issues related to S3 object storage, like nextcloud/server#11826 for example.

Best of luck.

P.S. If you manage to get the portion of the log file that includes debug info as per https://github.com/SergeyMosin/Appointments/issues/2#issuecomment-592293452  I would still like to take a look at it.

**Comment by small1** [comment] 2020-03-09 10:23
This is now working for me without any workarounds. So this from my end can be closed.

**Closed** 2020-04-20 22:12 UTC
