### ISSUE TITLE
[feature] add free text field

### ISSUE THREAD

**Issue by mokkin** [SergeyMosin/Appointments#24] opened 2020-03-09 20:03 UTC
At the end of the booking process the client booker should be able to add some free information in a textbox.

**Comment by legalstuff** [comment] 2020-08-11 11:02
I need a text field for the reason why an appointment should be booked

**Comment by legalstuff** [comment] 2020-08-11 11:06
A field for the title of a person (prof. / Dr. / Mr / mrs) as an example.
important in the business environment.

**Comment by RoundAboutWEB** [comment] 2020-09-20 10:33
A new feld as textarea in the form will be very posible so the customer can tell more informations why he need a date.

**Comment by nolens** [comment] 2020-09-28 09:52
@SergeyMosin 
Would love to see this, too.

**Comment by kojid0** [comment] 2020-10-22 15:55
An option to let the user set the name of the text field would be nice (header and the grey text hint inside the box as well). Keep up the great work! :)

**Comment by RoundAboutWEB** [comment] 2020-11-03 09:06
Is the additional free text field edited here or is there already another issue?

**function:**
an additional text field for a free input in the form.
Title: "Let's talk about:"

**Comment by SergeyMosin** [comment] 2020-11-03 13:04
I guest we can start with a simple json object setting that will rendered as HTML in the form, something like this:
```
{
  "tag": "textarea",
  "label": "Enter text",
  "placeholder": "placeholder text"
}
```
input (with some types like number or text, )
```
{
  "tag": "input",
  "type": "number"
  "label": "Enter number",
  "placeholder": "123456"
}
```
or for select drop down:
```
{
  "tag": "select",
  "label": "Make your choice",
  "options":[
     "Cars",
     "Tanks",
     "Mermaids"
  ]
}
```
One caveat is that the label will not be translated by default.

Any thing missing?

I'll try to add this over the upcoming weekend

**Comment by RoundAboutWEB** [comment] 2020-11-03 16:59
![grafik](https://user-images.githubusercontent.com/26809494/98016476-4f0bbc80-1dfe-11eb-9b4c-62ff6e97d4fc.png)

**Comment by RoundAboutWEB** [comment] 2020-11-17 06:52
Until when can I expect to use the function?

**Comment by SergeyMosin** [comment] 2020-11-17 13:00
Probably in the ext day or two

**Comment by RoundAboutWEB** [comment] 2020-11-17 13:20
Perfect - You make me happy

**Comment by SergeyMosin** [comment] 2020-11-21 05:15
v1.7.14 ``Settings > Customize Public Page > Advanced Settings > Form Designer (beta) > JSON Object``

See this post for examples https://github.com/SergeyMosin/Appointments/issues/24#issuecomment-721103321

This is a JSON object so watch your quotes ``"`` and commas ``,``

``<input>, <textarea> and <select>`` tags are supported, ``input``s and ``textarea``s can can be optional.

The text from the inputs is added to the event's description and also to **organizer's** emails


_P.S. I'll add a GUI at some point in the future._

**Comment by RoundAboutWEB** [comment] 2020-11-21 21:30
I installed your last update today - it works perfect. Thank you.

**Comment by Torenga** [comment] 2020-11-30 15:09
@SergeyMosin Thank you for the guide, I am able to set up fields as described with no JSON experience at all. Very good!

But with no experience I don't know how, or even if it's possible, to set up more fields. I'd like both a "notes" inputfield along with a drop-down menu of options. Is this possible?

**Comment by manugch** [comment] 2021-01-08 09:06
Good work so far. How can we add multiple custom fields? An array of objects dosen't seem to work yet.

**Comment by SergeyMosin** [comment] 2021-01-08 13:32
@manugch and @Torenga Multiple "extra" fields are not supported yet. The plan is to redesign the form first to look something like screenshots in #129 and then add a GUI form builder (probably [Vue-Form-Builder](https://vue-form-builder.herokuapp.com/)) to let users customize input fields.

**Comment by Vince2956** [comment] 2021-04-13 08:01
I saw that the text was limited to 255 characters, is it possible to increase this limit?

There are special characters that are returned in hexadecimal in the confirmation email. For example, (') gives (& # 039;)

**Comment by SergeyMosin** [comment] 2021-04-19 04:10
@Vince2956 Can you open a new issue for your request, otherwise it is all the way down here and I forget to take care of this. Thanks.
Closing...

**Closed by SergeyMosin** 2021-04-19 04:10 UTC

**Comment by evertvanvliet** [comment] 2021-05-19 07:40
Would it be possible to have multiple items? I would love to add some interaction in the form. e.g. Once somebody selected a category in the drop down menu, he/she get's a feed back on the number of timeslots he/she has to reserve.

**Comment by chrisv-dev** [comment] 2022-03-30 15:14
As far as i have seen, adding this extra field is only possible for the "main page". I think it would be a useful feature to have the option of adding additional fields for any of the pages (main page + "additional pages")

**Comment by KapriQ** [comment] 2022-04-21 11:44
How Can i add more than 1 field please? I am using latest nextcloud. I have tried to change State.php + PageController.php but they are different from what i have installed.

Can anyone help? Thanks

**Comment by SergeyMosin** [comment] 2022-04-21 12:32
@KapriQ Currently there is no "official" way to add more than one additional field. However there is:
1. Contributed PR code here: https://github.com/SergeyMosin/Appointments/pull/259 that works for some people.
2. An option to redirect a user to custom page after an appointment is confirmed as described here #315 which can be used to redirect a user to a Nextcloud Forms page https://apps.nextcloud.com/apps/forms for example, where the user can fill out additional questionnaires.

Going forward I think option 2 makes more sense, and we can work with the [Forms Team](https://github.com/nextcloud/forms) to improve integration.

**Comment by KapriQ** [comment] 2022-04-21 13:15
Appreciate your fast reply, but for my use case, i need to add 2 more fields :( ...
I think that many ppl are missing this feature... It's so problematic to add feature like this?

**Comment by Flashpok** [comment] 2022-10-05 13:13
I tried to apply the code snippet in Form Designer (beta), but no change in appointment form. Is it broken ? (Or missed I something ?)
Thank you for your help !
![json](https://user-images.githubusercontent.com/85504874/194068860-3d458c06-2dc1-4c57-a94d-167cc5f9aa83.png)

**Comment by Flashpok** [comment] 2022-10-09 14:15
Any idea from someone ?
Thank you.

**Comment by SergeyMosin** [comment] 2022-10-09 22:26
@Flashpok Is you Appointment page "Enabled". You will only see the extra fields when the page is Enabled and has appointments in range.

Enabled example:
![image](https://user-images.githubusercontent.com/10747559/194782282-7e8e0a73-eba7-4606-90b3-631df5666806.png)

Disabled example:
![image](https://user-images.githubusercontent.com/10747559/194782312-c4ff0fa8-5a5b-4e62-8d17-03f212ceae1d.png)

**Comment by Flashpok** [comment] 2022-10-28 07:09
> You will only see the extra fields when the page is Enabled and has appointments in range.

I confirm that : (1) the page is Enabled and (2) there are appointments in range.

Any idea ?

**Comment by WNYmathGuy** [comment] 2023-01-07 00:39
I'm having fun now
![Screenshot from 2023-01-06 19-34-33](https://user-images.githubusercontent.com/28640985/211122431-2e13f390-af11-4fe3-8b08-da830aeba41a.png)
```
{
  "tag": "textarea",
  "label": "Meeting Location (blank if Online)",
  "placeholder": "e.g. 123 Main St, 14221 \nor 68 Pine Ridge W., Eggertsville \nor Your Office \nor Wegmans on Sheridan in the dining room"
}
```

Can I preset the height of the `textarea`?

**Comment by martin-77** [comment] 2023-05-20 08:23
with the latest update, fields do not work anymore. No idea, how to solve this issue.

**Comment by SergeyMosin** [comment] 2023-05-20 12:49
@martin-77 I can not replicate this I checked both NC25 and NC26. Can you send me (sergey [at] srgdev.com) your settings dump `Settings > Advanced Settings > Debugging > Settings Dump`

My test:

Settings
![image](https://github.com/SergeyMosin/Appointments/assets/10747559/fa0bebea-bbaa-4cc4-996a-1d72ec4bdab7)

Form
![image](https://github.com/SergeyMosin/Appointments/assets/10747559/a1e3450d-9b4d-4078-ab13-1a9a9d21bbb3)

Booking
![image](https://github.com/SergeyMosin/Appointments/assets/10747559/f11a370e-948a-4e2b-8c4a-d6847b4c246e)

**Comment by martin-77** [comment] 2023-05-22 21:53
@SergeyMosin You got mail ;-)
Thanks

**Comment by SergeyMosin** [comment] 2023-05-22 22:30
@martin-77 I see now. Your issue is similar to this: https://github.com/SergeyMosin/Appointments/issues/24#issuecomment-1272641567 . There must be valid appointments with in "Show for next..." range and the page must be enabled in order for the extra fields to be displayed. In other words if the pages says "No Appointments Available" then the extra fields will NOT be displayed.

BTW, your "Fragen und Support" page shows the extra filed.

**Comment by martin-77** [comment] 2023-05-22 22:37
That was fast...
You are right, work when adding dates for possible appointments. 
Overread the comment below -> You will only see the extra fields when the page is Enabled and has appointments in range.

Thanks a lot for your answer an that great tool!

**Comment by OutbackMatt** [comment] 2023-06-27 01:18
This is really useful - thanks..

**Comment by taziobaker** [comment] 2023-10-18 16:38
Is it also possible to load the information helper into the right panel without having to loose the current setting?

This isn't clear. Sorry, here is an example:
When you click on "Manage Appointment Slots", there is a panel ("Calendars and Schedule") that shows up between the left menu and the "Public Page Preview"
Let's say you are filling out the settings, but get confused about one of the settings.
Luckily there is an *i* besides it and you click it to get clarity.
Actually, you are sent to the whole information page and loose the settings you had already started filling.

Would it be possible to have the *i* content show up next to the "Calendars and Schedule" so one may continue to fill the setting without loosing parameters already filled?

**Comment by taziobaker** [comment] 2023-10-18 17:32
I had changed my config.php with 'htaccess.RewriteBase' => '/', but the Public Page URL to the Appointment still shows '/index.php' in the url.

**Comment by ive-online** [comment] 2024-03-13 10:43
Hello!
I use this "issue" page because it links directly from the appointment form > "Advanced Form Settings" > "Extra Fields (JSON Object)".

Unfortunately, I didn't notice right away that with one of the last versions, information from additional fields is unfortunately not transferred to the appointment calendar. Until v1.15.5 it worked wonderfully.

Please may you have a look why.
Unfortunately, only one additional field is listed in the event entry. My form has 2 additional fields, but only the first field is listed in the event entry. Since the 2nd field is an important piece of content, the first one had to be deleted in the appointment form. Only the first additional field is included in the appointment description.

Thanks in advance !

**Comment by SergeyMosin** [comment] 2024-03-13 14:04
@ive-online thank you for the report, the bug is confirmed. Tracked here: #488

**Comment by Micha-Serv** [comment] 2024-03-30 15:16
> Good work so far. How can we add multiple custom fields? An array of objects dosen't seem to work yet.

[
  {
    "tag": "input",
    "required": true,
    "label": "Company Name",
    "placeholder": "Enter Company Name here",
    "type": "text"
  },
  {
    "tag": "input",
    "required": true,
    "type": "number",
    "label": "Number of participants",
    "placeholder": "Enter 1..."
  }
]

**Comment by SergeyMosin** [comment] 2024-03-30 19:48
@Micha-Serv Works for me, please make sure that you have bookable appointments and the page is enabled. 

![image](https://github.com/SergeyMosin/Appointments/assets/10747559/9d8981a0-901e-4f1e-b51a-800a1fd0ef3e)

**Comment by dpolakovics** [comment] 2024-10-18 19:45
Hello, i tried to enter a checkbox:
```json
[
  {
    "tag": "input",
    "required": true,
    "value": "test",
    "type": "checkbox"
  }
]
```
am i missing something or is this not supported at the moment?

thanks for the extension and best regards.

**Comment by SergeyMosin** [comment] 2024-10-18 21:09
> Hello, i tried to enter a checkbox...

Currently `checkbox` elements are not supported. If you open a new Feature request it will be on the dev. roadmap or some might submit a PR.

**Comment by dpolakovics** [comment] 2024-10-18 21:12
Than was quick.
Thanks.
Maybe i'll look a bit into the source if i will use this extension.

**Comment by 0x4E4448** [comment] 2024-11-24 22:05
Is there a way to use the value of these custom fields in the event title templates?

**Comment by jantheofel** [comment] 2025-07-13 20:21
I'd like to have hidden fields added.
Usecase: Prefill with campaign ID, affilaite ID, ...
Workaround: Use textfield and hide it using CSS.
