### ISSUE TITLE
Timezone falls back to Europe/London

### ISSUE THREAD

**Issue by armaccloud** [SergeyMosin/Appointments#274] opened 2021-12-20 18:56 UTC
I noticed that the displayed times are not correct when booking an appointment.
The appointment app shows that it is falling back to Europe/London and also shows this time-zone in the appointment slots.
I have already set the time zone correct in the Calendar settings, also in the config.php on the server.
What can be done to fix this?

**Comment by SergeyMosin** [comment] 2021-12-20 20:03
@armaccloud Can you please send me your settings dump, `Settings > Advanced Settings > Debugging > Settings Dump` to ( sergey [at] srgdev.com ) so I can try to reproduce this.

**Comment by armaccloud** [comment] 2021-12-21 06:55
Hi Sergey,

Thank you for your reply, hereby I send you the dump from the appointments' app.

Nextcloud Version

: 22.2.3

Appointments Version

: 1.11.8

Time zone

: Europe/Amsterdam (calendar: Europe/Amsterdam, core: UTC)

Key

: No

org_info

: array (
  'organization' => 'Free Coachee',
  'email' => '
***@***.***
',
  'address' => 'Videocall Link:
https://whereby.com/freecoachee
',
  'phone' => '',
)

email_options

: array (
  'icsFile' => true,
  'skipEVS' => true,
  'attMod' => true,
  'attDel' => true,
  'meReq' => false,
  'meConfirm' => true,
  'meCancel' => false,
  'vldNote' => '',
  'cnfNote' => '',
)

calendar_settings

: array (
  'mainCalId' => '29',
  'destCalId' => '3',
  'nrSrcCalId' => '29',
  'nrDstCalId' => '3',
  'nrPushRec' => true,
  'nrRequireCat' => false,
  'nrAutoFix' => false,
  'tmmDstCalId' => '3',
  'tmmMoreCals' =>
  array (
    0 => '5',
    1 => '8',
  ),
  'tmmSubscriptions' =>
  array (
  ),
  'tmmSubscriptionsSync' => '0',
  'prepTime' => '0',
  'whenCanceled' => 'mark',
  'allDayBlock' => false,
  'tsMode' => '2',
)

page_options

: array (
  'formTitle' => 'Book your appointment',
  'nbrWeeks' => '4',
  'showEmpty' => false,
  'startFNED' => false,
  'showWeekends' => false,
  'time2Cols' => true,
  'endTime' => false,
  'hidePhone' => false,
  'showTZ' => false,
  'gdpr' => '',
  'pageTitle' => '',
  'pageSubTitle' => '',
  'metaNoIndex' => false,
  'pageStyle' => '',
)

more_pages

: NULL

pages

: array (
  'p0' =>
  array (
    'enabled' => 1,
    'label' => '',
  ),
)

dir_info

: array (
)

reminders

: array (
  'data' =>
  array (
    0 =>
    array (
      'seconds' => '0',
      'actions' => true,
    ),
    1 =>
    array (
      'seconds' => '0',
      'actions' => true,
    ),
    2 =>
    array (
      'seconds' => '0',
      'actions' => true,
    ),
  ),
  'friday' => false,
  'moreText' => '',
)

appt_talk

: array (
  'enabled' => false,
  'delete' => false,
  'emailText' => '',
  'lobby' => false,
  'password' => false,
  'nameFormat' => 0,
  'formFieldEnable' => false,
  'formLabel' => '',
  'formPlaceholder' => '',
  'formTxtReal' => '',
  'formTxtVirtual' => '',
  'formTxtTypeChange' => '',
  'formDefLabel' => 'Meeting Type',
  'formDefPlaceholder' => 'Select meeting type',
  'formDefReal' => 'In-person meeting',
  'formDefVirtual' => 'Online (audio/video)',
)

fi_json

: array (
)

fi_html

: array (
  0 => '',
)

useDefaultEmail

: NULL

emailFixOpt

: NULL

template_info

: array (
  'old_info' =>
  array (
    'tzName' => 'Europe/Amsterdam',
    'tzData' => 'BEGIN:VTIMEZONE
TZID:Europe/Amsterdam
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE',
  ),
  'p0' =>
  array (
    'tzName' => 'Europe/Amsterdam',
    'tzData' => 'BEGIN:VTIMEZONE
TZID:Europe/Amsterdam
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE',
  ),
)

template_data

: array (
  'p0' =>
  array (
    0 =>
    array (
    ),
    1 =>
    array (
      0 =>
      array (
        'start' => 52200,
        'dur' =>
        array (
          0 => 30,
        ),
        'title' => '',
      ),
      1 =>
      array (
        'start' => 46800,
        'dur' =>
        array (
          0 => 30,
        ),
        'title' => '',
      ),
      2 =>
      array (
        'start' => 57600,
        'dur' =>
        array (
          0 => 30,
        ),
        'title' => '',
      ),
      3 =>
      array (
        'start' => 64800,
        'dur' =>
        array (
          0 => 30,
        ),
        'title' => '',
      ),
    ),
    2 =>
    array (
    ),
    3 =>
    array (
      0 =>
      array (
        'start' => 57600,
        'dur' =>
        array (
          0 => 30,
        ),
        'title' => '',
      ),
      1 =>
      array (
        'start' => 52200,
        'dur' =>
        array (
          0 => 30,
        ),
        'title' => '',
      ),
      2 =>
      array (
        'start' => 46800,
        'dur' =>
        array (
          0 => 30,
        ),
        'title' => '',
      ),
      3 =>
      array (
        'start' => 64800,
        'dur' =>
        array (
          0 => 30,
        ),
        'title' => '',
      ),
    ),
    4 =>
    array (
    ),
    5 =>
    array (
    ),
  ),
)

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by armaccloud** [comment] 2021-12-21 07:16
@SergeyMosin 
I have sent you the dump from the settings.

Strangely, at this moment I don't get the message anymore, and it now defaults to the correct time zone from what I can see in the right-top from the weekly template settings.

Maybe this has to do with me setting the default time zone in the config.php settings of Nextcloud yesterday. Strangely, it did default back into Europe/London _after_ I configured that setting several times. So maybe the issue will recur again at some point.

I find the following events in the logs, which might have something to do with it. The calendar is a shared calendar that I use, maybe it cannot find the calendar due to that reason?
![image](https://user-images.githubusercontent.com/9272078/146887528-5827f69f-f846-451d-ba95-acac5fcd3534.png)

**Comment by SergeyMosin** [comment] 2022-01-19 15:51
Closing for now but will keep an eye out for errors in time zone detection algo, maybe even add user override option in the future.

**Closed by SergeyMosin** 2022-01-19 15:51 UTC

**Comment by xeruf** [comment] 2022-05-05 12:02
I had this for my personal calendar where it detected the timezone automatically. Setting it manually in the calendar app fixed it.

**Comment by SergeyMosin** [comment] 2022-05-05 12:09
This is a know issue with **"Personal"** calendars because during user creation `timezone` is not set (null) in NC Database. I think I filed this issue with NC team. Here is my DB screen shot:

![image](https://user-images.githubusercontent.com/10747559/166919751-4ae4a565-815d-4173-9a33-5e5c92f4c1fb.png)

ref: #243

**Comment by SergeyMosin** [comment] 2022-05-09 14:45
Just FYI:

There are already 2 fallbacks like so:
1. Per calendar ( not available for `Personal` calendar )
2. From Calendar App `getUserValue($userId, 'calendar', 'timezone')` 
3. From NC Core `getUserValue($userId, 'core', 'timezone')`

Values can be checked in  `Settings > Advanced Settings > Debugging > Settings Dump` and would look like  this:
```
Nextcloud Version: 23.0.3
Appointments Version: 1.12.3
Time zone: America/New_York (calendar: N/A, core: America/New_York)
```

If the 3 methods above can not determine a valid time zone, NC's `getDefaultTimeZone` function is used which will most likely return `UTC` and if so it will result in the final fallback to `Europe/London` time zone.
