### ISSUE TITLE
Automatically release time slot if not confirmed by email

### ISSUE THREAD

**Issue by r3dnib** [SergeyMosin/Appointments#393] opened 2023-01-15 02:40 UTC
Hello,

I have a question:

Condition: "Skip email validation step" is unchecked.

Is it possible to set or add the following to the app:

If someone books an appointment but does not confirm it by mail, the booking is discarded and free for other people.
Maybe after one or after two hours.

Could you implement that or could you tell me how to configure that?

Your app is really great. Thank you very much for your work.

Unfortunately I am not a programmer, so my request.

Many greetings, Dave

**Comment by SergeyMosin** [comment] 2023-01-16 13:55
This feature is on the roadmap for v2
Closing as duplicate of #104

**Closed by SergeyMosin** 2023-01-16 13:55 UTC
Labels: duplicate
