### ISSUE TITLE
Second layer for cancellation links needed (Antivirus checks make the use of Appointments impossible)

### ISSUE THREAD

**Issue by jacotec** [SergeyMosin/Appointments#293] opened 2022-02-09 08:29 UTC
I found that some customers are never able to book an appointment at all. All selected appointments are automatically canceled after a very short time although the customer did nothing.

Investigating the root cause for this I found that the issue is the fact, that the "cancel" link in the confirmation email works immediately once it's simply called.

Many customers have an antivirus / antimalware scan on their email server which checks if any links in the mail are malicious. And just that check cancels the appointment immediately without any human background action - which makes Appointments unusable.

(The same happens to the confirmation link as well)

For every link which is sent via email there should be a second confirmation layer on the App's web page:

When the confirmation link is clicked, the website should show the appointment data with "Do you would like to confirm the appointment - Yes/No" buttons.

But even more important, for the cancellation link the web page should show the appointment data with "Do you want to cancel your appointment - Yes/No".

This would make Appointments really usable for everyone running antivirus checks on their email servers.

**Comment by SergeyMosin** [comment] 2022-02-09 13:12
Thanks for the report. I'll add a fix for this into the next release.

However, I think only the "Yes" button is needed, because it is unclear what is expected to happen when the "No" button is clicked.

**Comment by jacotec** [comment] 2022-02-09 13:15
@SergeyMosin Agree! At least there yould be one more action on the web page.
Thanks for adding!

**Comment by SergeyMosin** [comment] 2022-02-14 15:27
available in v1.11.14

![image](https://user-images.githubusercontent.com/10747559/153892292-f8e11155-31a1-40a8-a716-7716ee4f05e5.png)

![image](https://user-images.githubusercontent.com/10747559/153892689-c719258a-bebe-4a99-9a52-92773d71e84d.png)

![image](https://user-images.githubusercontent.com/10747559/153893151-04fdf34e-59c7-4363-ab86-3f04b6829a27.png)

**Closed by SergeyMosin** 2022-02-14 15:27 UTC

**Comment by caichat** [comment] 2025-03-05 11:18
Hi @SergeyMosin !

A few days ago, I notices that Virus/Spam-Protection (in my case O365) now follows every Link an even the Links on the linked Webpage. Therefore the implemented "Second Layer" isn't sufficient.
While looking for a workaround, I've noticed that the Crawling Agents/Bots are only using the HTTP-Command HEAD - they don't check the Content, it seems they only check for the existance of links.
So I blocked all HEAD-Commands that are sent to the NextCloud-Page, and solved it. But now other things can't also use the HEAD Command.
I think it would be good to implement this into the Callback-Method "cncf". Cause there shouldn't be any use-case, why a HEAD-Call should trigger any code-execution.
What to you think about this solution?

Regards, Christian

**Comment by caichat** [comment] 2025-03-14 09:52
Hi @SergeyMosin! Thanks for your answer.
Since the solution with my first use-case is running for 1 week now, i've a lot of log-files to crawl through.
can you tell me, which cncf-parameters determine whether a call is a cancellation, or a accept?
that information would make it much easier, to filter the files.
thanks!

**Comment by caichat** [comment] 2025-03-14 10:11
Hi @SergeyMosin!
Here are a few Calls, filtered by cncf?d=0. Hope this is the right filter for the cancellations.
Unfortunately User-Agent field ist empty in this calls! in other log rows there is a value, so logging should be OK.

What I've done so far:
* Setting Header via Apache
`Header set X-Robots-Tag "noindex, nofollow"`

*Rewrite-Rule to deny HEAD-Calls
```
RewriteCond %{REQUEST_METHOD} ^HEAD$
RewriteRule ^ - [F]
```

After my changes, the users were able to use the app without any problems.
The Users where the Mail with the Link could not be scanned anymore, didn't got the confirmation mail, but the appointment didn't get cancelled either, which is good so far.
The domains which with frequent problems and unconfirmed appointments are: *@outlook.com, *@hotmail.com > Microsoft.
Surprise -> look at the IP-Info: 
* 104.47.11.62, 104.47.11.254: https://ipinfo.io/ips/104.47.11.0/24

Logs are from the day, where I've done some testing:
```
/var/log/apache2/master_log_detailed.log.10.gz:104.47.11.126 - - [04/Mar/2025:15:23:50 +0100] "HEAD /index.php/apps/appointments/pub/ZM7AlVMc03Za7bzD/cncf?d=0zlsyRzGx9LBeaK0h5TMVh%2FlX9qUkmp2FrzNbxgVUWia1eff6VBtDsA6sMaF1UwEmiHCXcx%2FXmg%3D%3D HTTP/1.1" 200 5031 "-" "-"

# Test-User has clicked ACCEPT before the Bot!
/var/log/apache2/master_log_detailed.log.2.gz:104.47.11.62 - - [12/Mar/2025:22:11:58 +0100] "HEAD /index.php/apps/appointments/pub/ZM7AlVMc03Za7bzD/cncf?d=0jE8%2BoApQ2MfmDb7U66ICHAe5bU3gfkXRxT%2FRiyU1Gear2oMN1ooqkUmGGFfNecwhb8m10vg2fA%3D%3D HTTP/1.1" 403 3517 "-" "-"
/var/log/apache2/master_log_detailed.log.9.gz:104.47.11.62 - - [05/Mar/2025:07:41:16 +0100] "HEAD /index.php/apps/appointments/pub/ZM7AlVMc03Za7bzD/cncf?d=0zlsyRzGx9LBeaK0h5TMVh%2FlX9qUkmp2FrzNbxgVUWia1eff6VBtDsA6sMaF1UwEmiHCXcx%2FXmg%3D%3D HTTP/1.1" 200 5033 "-" "-"
/var/log/apache2/master_log_detailed.log.9.gz:104.47.11.62 - - [05/Mar/2025:07:45:38 +0100] "HEAD /index.php/apps/appointments/pub/ZM7AlVMc03Za7bzD/cncf?d=051veFKizPNQKzlBW2vWeRp6tgvxJy5gDV5nYrwV7Msxz63rz9DOYAR8kLFFMw%2FIAcABFyl%2BnCQ%3D%3D HTTP/1.1" 200 5033 "-" "-"
/var/log/apache2/master_log_detailed.log.9.gz:104.47.11.62 - - [05/Mar/2025:11:25:31 +0100] "HEAD /index.php/apps/appointments/pub/ZM7AlVMc03Za7bzD/cncf?d=0PCq95IXuobIzExLrOtved97cgCQyzhLxkF4zovY3j7%2F%2BjulY6U%2BOJnNj5UY8MyaxgDP43uyhAA%3D%3D HTTP/1.1" 200 5031 "-" "-"
/var/log/apache2/master_log_detailed.log.9.gz:104.47.11.254 - - [05/Mar/2025:11:31:53 +0100] "HEAD /index.php/apps/appointments/pub/ZM7AlVMc03Za7bzD/cncf?d=0PCq95IXuobIzExLrOtved97cgCQyzhLxkF4zovY3j7%2F%2BjulY6U%2BOJnNj5UY8MyaxgDP43uyhAA%3D%3D HTTP/1.1" 200 5029 "-" "-"

# First log after making changes from above.
/var/log/apache2/master_log_detailed.log.9.gz:104.47.11.254 - - [05/Mar/2025:11:42:45 +0100] "HEAD /index.php/apps/appointments/pub/ZM7AlVMc03Za7bzD/cncf?d=0C%2B1CpTk4UTm%2Ffw3GZXbwR5CbmZeog5IENYrs6RMcibAjSEp8%2F4GDjJGwNBL4nmKKy6KJh%2FYH9w%3D%3D HTTP/1.1" 403 3517 "-" "-"
r
```

**Comment by SergeyMosin** [comment] 2025-03-14 15:42
@caichat Thanks for the info. The `HEAD` requests are most likely related to MS Safe Links ( https://learn.microsoft.com/en-us/defender-office-365/safe-links-about?view=o365-worldwide#safe-links-settings-for-email-messages ). I think the solution here would be to accept the `HEAD` requests, show the UI components as usual, but skip the actual backend flow/actions that make changes (confirm, cancel, etc...) to the data. I'll try to include it into the next release.

**Comment by caichat** [comment] 2025-03-14 20:11
HI @SergeyMosin , thanks a lot.
If you need me to do some testing, just tell me.
Regards, Christian
