### ISSUE TITLE
Booking fails with 500 due missing template

### ISSUE THREAD

**Issue by hrdinka** [SergeyMosin/Appointments#526] opened 2024-06-28 09:15 UTC
Hi,

many of my appointment pages do not work. When I try to book an appointment, it fails with 500 and the following log entry:

```
Error    appointments       Can't find template dur: 2, 23
```

Sometimes they work first and stop working after changing some settings, it does however not depend on a specific setting. Don’t know what to do, recreating does not help.

**Comment by SergeyMosin** [comment] 2024-06-28 10:50
It looks like the error happens when the time-slot requested by the attendee is being verified against the weekly template. 
Can you send me ( sergey [at] srgdev.com ) a settings dump ( `page settings > Advanced > Debugging > Settings Dump` ) for one of the pages that have appointments with multiple durations.

**Comment by SergeyMosin** [comment] 2024-06-28 11:00
If there are no pages with multiple durations the a page with most time-slots. Thanks.

**Comment by SergeyMosin** [comment] 2024-07-02 01:34
Thank you for sending the `Settings Dump` but I can not replicate this bug. However, I have added the `Log template durations` debugging mode.

![image](https://github.com/SergeyMosin/Appointments/assets/10747559/83798cea-ffcf-4929-b92a-09c982fbcf0a)

When the `Log template durations` mode is activated it will log something like the testing image below. @hrdinka if you can trigger the bug when the `Log template durations` is active can you please send me the `template debug` log entries.

![image](https://github.com/SergeyMosin/Appointments/assets/10747559/db57fd95-d9f5-4df4-990d-154c0e1d21f0)

**Comment by hrdinka** [comment] 2024-07-02 07:38
Here it is:

![image](https://github.com/SergeyMosin/Appointments/assets/1436960/51d64edd-a0f7-484c-bd36-8b8a8272a292)

This is from the minimal test case (no changes to default settings, just selected a calendar + added one timeslot),

Thanks a lot for your support @SergeyMosin

**Comment by SergeyMosin** [comment] 2024-07-02 13:40
Bug confirmed. This happens when there are more than 10 pages and pages with ids more that 9 (ex. p11) use `Template Mode`. The fix will be included in the next release.

**Comment by hrdinka** [comment] 2024-07-02 13:42
Thanks a lot for your time and great software Sergey :pray:

**Comment by SergeyMosin** [comment] 2024-07-28 20:56
fixed v2.1.6

**Closed by SergeyMosin** 2024-07-28 20:56 UTC
Labels: bug
