### ISSUE TITLE
Do not schedule appointments when calendar has an all-day event marked as busy

### ISSUE THREAD

**Issue by dbolton** [SergeyMosin/Appointments#231] opened 2021-07-16 16:06 UTC
If you have an all-day event in your calendar and that event is marked as "show as busy" (instead of "show as free"), the Appointments app should not let people schedule an appointment on that day.

**Comment by nolens** [comment] 2021-07-30 12:07
Same issue as this one 
https://github.com/SergeyMosin/Appointments/issues/226

**Comment by SergeyMosin** [comment] 2021-08-08 17:06
Closing as a duplicate of #226

**Closed by SergeyMosin** 2021-08-08 17:06 UTC
Labels: duplicate

**Comment by nolens** [comment] 2021-08-09 06:29
@SergeyMosin 

You have closed both issues now - was this intentional? Is the described behaviour intentional? 

Best
Tom

**Comment by SergeyMosin** [comment] 2021-08-09 10:15
@nolens #226 is open
