### ISSUE TITLE
Calendar Updates Outside of App

### ISSUE THREAD

**Issue by LittleDuke** [SergeyMosin/Appointments#100] opened 2020-06-17 15:19 UTC
I just added a lot of open availability slots via my desktop (Mac) calendar and set them as recurring weekly.  So much easier to manage availability via that tool.

Is there away to have your app scan that linked calendar and auto-populate your database?

<img width="1036" alt="Screen Shot 2020-06-17 at 10 18 47" src="https://user-images.githubusercontent.com/1402517/84916674-f83a5c00-b083-11ea-8d83-dfa776090124.png">

**Comment by SergeyMosin** [comment] 2020-06-17 16:47
Not at the moment, but definitely something to look into. 

P.S. Next major release will probably have some sort of weekly template that would only need to be set once.

**Comment by LittleDuke** [comment] 2020-06-17 16:53
That would be very helpful to have a template.

But if you could scan the calendar for the word "Available" to synchronize that would be awesome and have greater utility IMHO instead of spending too much time building your own calendar management function :-) 

We're happy to pay / donate to the project because we think it would be incredibly valuable.

**Comment by krheinwald** [comment] 2020-06-17 17:04
Or the other way round… Scan a calendar for free timeslots and assign appointments to them as they fit.

**Comment by LittleDuke** [comment] 2020-06-17 17:10
> Or the other way round… Scan a calendar for free timeslots and assign appointments to them as they fit. 

The challenge here would be time-boxing it, but yes I could see pointing it at the group calendar and then filling in around that with options.

We prefer however to have an Appointments only calendar that we can turn on and off since our team calendar would get cluttered up.

Also no point in keeping past/expired appointment slots which can be deleted in the calendar itself  or set a feature to "auto-purge" the Available slots but leave any that had been scheduled for posterity/archiving.

**Comment by krheinwald** [comment] 2020-06-17 17:19
Different Use Cases, I guess ;)

 

I am now using Calendly and – as a solo consultant – I like the simplicity of making my free time automatically available for customer meetings/appointments.

**Comment by LittleDuke** [comment] 2020-06-17 17:25
_> Different Use Cases, I guess ;) I am now using Calendly and – as a solo consultant – I like the simplicity of making my free time automatically available for customer meetings/appointments._ 

I started with that but found it annoying to have to manage the calendar separately.

The nextcloud built in calendar is an AWESOME replacement to MS Exchange and this app really fulfills the use case without having to pay for outside services / a separate login and calendar to manage, not to mention all the data leakage using a third party site can lead to.

I would seriously pay the equivalent fee to the developer for the pro version of calendly.

**Comment by SergeyMosin** [comment] 2020-06-17 17:34
@LittleDuke 
> ... if you could scan the calendar for the word "Available" to synchronize 

Using word "Available" might be in conflict with #97 if that feature is implemented. Is it hard to set event's "Category" to "Appointment" for example, in "(Mac) calendar" so that would be the "trigger" for synchronization ?

Plus there are different languages

**Comment by SergeyMosin** [comment] 2020-06-17 17:55
Similar to #39

**Comment by LittleDuke** [comment] 2020-06-17 18:08
> @LittleDuke
> 
> > ... if you could scan the calendar for the word "Available" to synchronize
> 
> Using word "Available" might be in conflict with #97 if that feature is implemented. Is it hard to set event's "Category" to "Appointment" for example, in "(Mac) calendar" so that would be the "trigger" for synchronization ?
> 
> Plus there are different languages

I was only using that as an illustrative example :-)

You could also simply copy in a UUID into the notes section as well that would solve it.

-dvd

**Comment by nolens** [comment] 2020-06-20 09:38
> I would seriously pay the equivalent fee to the developer for the pro version of calendly.

@LittleDuke 

For funding, @SergeyMosin has made available this page: 
https://www.srgdev.com/gh-support/nextcloudapps 

I have funded this project as well and I am sure Sergej has put a lot of work and will continue to do so. So I would like to encourage everyone to fund ongoing development via the link above.

**Comment by nolens** [comment] 2020-06-20 09:39
Good feature request from my point of view.

**Comment by a162624** [comment] 2020-06-28 12:18
one thumbs up for managing the calendar externaly. i sync with outlook via caldav which also has management of approved or canceled. or simply display all events with a certain category?

**Comment by a162624** [comment] 2020-06-29 11:37
Hi Claudius
Thanks for shareing. Do you also use CalDavSync to sync to Nextcloud?
Don't your run in to things likte [this](https://github.com/SergeyMosin/Appointments/issues/101#issue-646904460)?

**Comment by SergeyMosin** [comment] 2020-06-29 13:55
> Status needs to be preliminary
Show as "available"
Needs a category "Appointment"

Just FYI ``ORGANIZER`` must have ``SCHEDULE-AGENT=CLIENT`` otherwise email notifications might not work.

**Comment by ccoenen** [comment] 2020-06-29 14:24
I did get a few reports that email notifications were sketchy (i use simple notifications with no further confirmation, so this never really bothered me enough to chase down) But that's good to know.

**Comment by SergeyMosin** [comment] 2020-07-04 15:40
"External Mode" is available in v1.6.0 ``Manage Appointment Slots > Advanced Settings > Time slot mode``

**Two calendars are required**: a _Source Calendar_ to keep track of your availability timeslots and a _Destination Calendar_ for booked appointments.

Nextcloud's Calendar App or any other CalDAV compatible client can be used to add "available" timeslots into the _Source Calendar_. Most **recurrence rules are supported** in this mode.

Any event with "Category" set to **Appointment** (in Engilsh) **AND** "Show As" a.k.a. "Time As" a.k.a. "Free/Busy" a.k.a. "Time Transparency" set to **Free** (RFC5545 specs "TRANSP:TRANSPARENT") will be available for booking in the public form.

![app-v1 6 0-external-settings](https://user-images.githubusercontent.com/10747559/86515838-f72a5e00-bde9-11ea-936e-0174aa4957e2.jpg)

**Comment by SergeyMosin** [comment] 2020-07-04 15:43
@krheinwald I am going to reopen #87 for the "Template Mode"

**Comment by nolens** [comment] 2020-07-04 18:45
I am using Mac Calendar App on latest Mac OSX. 

- I am not able to set "Appointment" category in Mac Calendar App. There simply is no entry for "categories". As a consequence, Mac users don't seem to be able to use the new "external" mode. 

I was also trying a workaround: 
- Copy a calendar entry that is showing in / was created by nextcloud appointment app. But when copying such an entry on a synched Mac Calendar, entries seem to lose the "Appointment" category attribute and therefore do not show in nextcloud appointment App.

@SergeyMosin 
Is there anything that can be done to make the "external" feature work with OSX Calendar App?

**Comment by LittleDuke** [comment] 2020-07-04 18:50
> I am using Mac Calendar App on latest Mac OSX.
> 
> * I am not able to set "Appointment" category in Mac Calendar App. There simply is no entry for "categories". As a consequence, Mac users don't seem to be able to use the new "external" mode.

I also am on Mac and what I had to do was create the appointments on Monday and set to custom recurring so that i could get them to repeat M-T then I went Calendar on NextCloud and was able to set the category there and "Apply to All"

Worked like a charm!

And Kudo's to the Dev for the clever idea to separate the Schedule calendar from the Booked calendar!

**Comment by LittleDuke** [comment] 2020-07-04 18:53
> > I would seriously pay the equivalent fee to the developer for the pro version of calendly.
> 
> @LittleDuke
> 
> For funding, @SergeyMosin has made available this page:
> https://www.srgdev.com/gh-support/nextcloudapps
> 
> I have funded this project as well and I am sure Sergej has put a lot of work and will continue to do so. So I would like to encourage everyone to fund ongoing development via the link above.

Done and Done!  Should have an option to enter another amount ;-)

I'll just be sure to keep donating with updates!

-dvd

**Comment by nolens** [comment] 2020-07-04 19:38
> I also am on Mac and what I had to do was create the appointments on Monday and set to custom recurring so that i could get them to repeat M-T then I went Calendar on NextCloud and was able to set the category there and "Apply to All"

Thanks for your suggestion! 
BUT: 
- That requires to go back to the nextcloud backend. Not too elegant. 
- That is only a "solution" for "recurring" events. The initial idea was to be able to set single events, too. That does not seem to be possible from the OSX calendar app - or am I missing something?

**Comment by LittleDuke** [comment] 2020-07-04 20:28
> * That requires to go back to the nextcloud backend. Not too elegant.
> * That is only a "solution" for "recurring" events. The initial idea was to be able to set single events, too. That does not seem to be possible from the OSX calendar app - or am I missing something?

Right, not ideal for sure, but in theory you should be able to cut-copy-paste another entry and it probably drags the attributes along?   Clearly the built in Mac Calendar app doesn't seem to know anything about the RFC compliant Categories.  There's probably a more pro Calendar app for Mac but I have not bothered looking for one since the built in to this point has been totally sufficient for my needs.   I don't even know if its pluggable (like the mail client can have additional modules added like GPG etc)

**Comment by SergeyMosin** [comment] 2020-07-04 21:24
>  to be able to set single events, too

Single events CAN be set as long as they are _Free_ and have _Appointment_ category.

Since Mac Calendar App does not support "Categories" [rfc5545#section-3.8.1.2](https://tools.ietf.org/html/rfc5545#section-3.8.1.2) I can make _Appointment_ category optional.
A couple of check-boxes in the ``External mode settings``, something like:

``Do not require Appointment category`` for the Source calendar

and

``Any "Busy" event can block`` for the Destination calendar

@LittleDuke Thanks

**Comment by nolens** [comment] 2020-07-05 09:22
> something like:
> 
> `Do not require Appointment category` for the Source calendar
> 
> and
> 
> `Any "Busy" event can block` for the Destination calendar

I have just tested this scenario from OSX Calendar App. 
Any Calendar entries created by the app are marked "busy" in nextcloud calendar. 

As a consequence, a different solution is needed.

How about filtering for a naming convention? Something like 

`all entries containing a string like "free slot"` 

and

`Any "Busy" event can block` for the Destination calendar ?

**Comment by ccoenen** [comment] 2020-07-05 15:21
This will not work well with an international audience. Granted, "Appointment" categoriy is english, too, but it's not as important as the title.

**Comment by LittleDuke** [comment] 2020-07-05 15:59
What if the word Appointment is then instead used as the name of the event or in the notes?
<img width="323" alt="Screen Shot 2020-07-05 at 10 58 38" src="https://user-images.githubusercontent.com/1402517/86536600-8b5df900-beae-11ea-82b0-313963a5da03.png">

**Comment by SergeyMosin** [comment] 2020-07-06 13:28
In v1.6.1 "Appointment" category is optional, but this functionality is available for user who want more control via ``Manage Appointment Slots > External Mode Settings > Require "Appointment" category``

Available time-slots MUST be marked as **Free** otherwise Free/Busy reports will not work and there is going to be trouble any kind of group/sharing environment. See #57 for example...

However, for the external clients that do not allow users to set Free/Busy I can:
Add some kind of ``Fix time-slots`` button. Which would scan events where summary/name start with "\_" like ``_free abc`` for example and set ShowAs to "Free" and add  "Appointment" category.
This can probably be done automatically when an event is created, but I like the button approach better. 

P.S. This should also play nicely with #97 where if the last character is the "\_" as well, the text can be displayed as an _Appointment Title_.

**Comment by nolens** [comment] 2020-07-06 20:11
> Add some kind of `Fix time-slots` button. Which would scan events where summary/name start with "_" like `_free abc` for example and set ShowAs to "Free" and add "Appointment" category.
> This can probably be done automatically when an event is created, but I like the button approach better.

In my mind, automatic scanning would be even better, because it would fit those workflows better, where users want to manage their entire appointment process from their native calendars, _without_ using the nextcloud backend. 

From a users perspective, this would be very beneficial and convenient, no?

**Comment by SergeyMosin** [comment] 2020-07-14 16:54
``Appointment Slots > External Mode Settings > Auto-fix "Source" timeslots`` in version 1.6.3

If this option is enabled **AND the first character of the Description/Notes is "_"** then the Free/Busy will be set to "Free" and "Appointment" category will be added automatically when a new event is created in the "Source" calendar.

P.S. _Gnome Calendar requires additional work around_

**Comment by nolens** [comment] 2020-07-14 17:25
@SergeyMosin 

- I have installed latest version 1.6.3
- I am adding a new calendar item in my MacOs Calendar App with an underscore "_" in the source calendar
- I am synching the MacOS calendar with nextcloud calendar
- new calendar entry is showing in nextcloud calendar app in the source calendar
- but it is is set to "busy" - so it does not show in the public frontend as a bookable timeslot


What am I missing?

**Comment by SergeyMosin** [comment] 2020-07-14 17:34
@noles can I see the .ics file?

**Comment by nolens** [comment] 2020-07-14 17:39
There is no .ics file created in this process, I believe... 

Or where can this be downloaded?

**Comment by nolens** [comment] 2020-07-14 17:41
Here you go...

[FB6F7EA7-DAF3-4D57-B6B4-5FB55677A6E5.ics.zip](https://github.com/SergeyMosin/Appointments/files/4920331/FB6F7EA7-DAF3-4D57-B6B4-5FB55677A6E5.ics.zip)

**Comment by SergeyMosin** [comment] 2020-07-14 17:54
@nolens The event has the following line ``SUMMARY:_superevent`` whish is used for titles as per #97 
"Auto-fix" requires ``DESCRIPTION:_abc...``, I think it is called "Notes" on Macs 

<img src="https://user-images.githubusercontent.com/10747559/87459112-f27b5c00-c5d8-11ea-95b8-9bfb35fc1a78.jpg" width="256">

**Comment by SergeyMosin** [comment] 2020-07-14 17:56
It also only works when an event is created for the first time.

**Comment by nolens** [comment] 2020-07-14 18:08
So I summarize (tested on MacOS Calendar app):

- **Description** (!) of the event needs an underscore "_" as the first character
- **Title** of the event can be anything/ chosen freely 
- calendar entry can even be copied

Works like a charm, thanks!

**Comment by nolens** [comment] 2020-07-16 10:45
I am now using the "external Mode", and the booking process works fine!!

However, there is one little glitch:

If an attendee books an appointment, 

- the new booked slot shows in the target calendar (so far, so good, intended behavior)
- BUT the formerly open slot from the source calendar **remains visible** in the source calendar (but is _not_ bookable for other attendees, which is good) 

In my opinion, booked slots should be _deleted_ in the source calendar, which used to be the behavior before "external mode" was introduced. 

@SergeyMosin 
Any chance to restore that ?

Very good work, overall!!

Best
Thomas

**Comment by SergeyMosin** [comment] 2020-07-16 14:11
> ... booked slots should be deleted in the source calendar...

The source calendar is a sort of a (hidden) template or a placeholder, and unfortunately deleting booked time-slots from it in "external mode" is infeasible.

Let's say you have a booked appointments at 14:00 and an open time-slot at 16:00, and your client wants to reschedule the appointment to 16:00. You can just simply drag-and-drop the appointment (in the destination calendar) to 16:00 using a calendar app, and this will open-up the 14:00 time-slot and  the 16:00 slot will be blocked-off. Would the 14:00 time-slot have been deleted, the code for implementing this simple operation, would be over complicated and bug prone.

**Comment by LittleDuke** [comment] 2020-07-16 14:19
I agree with developer (though I'm pretty sure they could be deleted) -- I just "hide" the base appointment calendar from regular view unless i want to update availability.

As long as the system is not allowing people to double-book against it I'm completely satisfied the the current implementation.

Now the my question is this:  Can we have multiple overlapping options?  

For example I want to have a calendar with 20 minute slots available for introductory calls but ALSO want to have a calendar with 60 minute slots for people I already know (existing customers) so if someone books a 20 minute slot the 60 minute option for that hour would no longer be available.

**Comment by SergeyMosin** [comment] 2020-07-16 14:53
> ...have a calendar with 20 minute slots available for introductory calls but ALSO want to have a calendar with 60 minute slots...
Now the my question is this: Can we have multiple overlapping options?

This should be possible when #81 is implemented

**Comment by LittleDuke** [comment] 2020-07-16 15:25
> > ...have a calendar with 20 minute slots available for introductory calls but ALSO want to have a calendar with 60 minute slots...
> > Now the my question is this: Can we have multiple overlapping options?
> 
> This should be possible when #81 is implemented

Great -- started watching that as well -- that has high value to me so will tip generously when available :-)

-dvd

**Comment by nolens** [comment] 2020-08-12 11:48
@LittleDuke 
Would you like to close this issue, since the functionality has been successfully implemented?

**Closed** 2020-09-11 19:19 UTC
