### ISSUE TITLE
Error message: rts: array (\n)

### ISSUE THREAD

**Issue by fermat2a** [SergeyMosin/Appointments#487] opened 2024-03-11 16:47 UTC
Hi,

Nextcloud Version: 28.0.2
Appointments Version: 2.0.2

Problem:
Quite often I see an error message like the following in my log:

`
{
  "reqId": "XXXXXXXXXXXXXXXXX",
  "level": 3,
  "time": "2024-03-07T07:10:03+00:00",
  "remoteAddr": "",
  "user": "--",
  "app": "appointments",
  "method": "",
  "url": "--",
  "message": "rts: array (\n)",
  "userAgent": "--",
  "version": "28.0.2.5",
  "data": {
    "app": "appointments"
  },
  "id": "xxxxxxxxxxxx"
}
`

Can you give me an idea how I can find out what is the root cause?

bests

Sascha

**Comment by SergeyMosin** [comment] 2024-03-13 14:02
This should have been fixed in v2.0.1 , duplicate of #482

**Closed** 2024-04-13 17:12 UTC
