### ISSUE TITLE
Feature Request - Thank you

### ISSUE THREAD

**Issue by imaddaou76** [SergeyMosin/Appointments#474] opened 2024-01-25 15:27 UTC
1- Let's say a customer wants to change the appointment, do they need to schedule new one? Is there a way to include a link in the email to allow them re-schedule if they need to?

2- Let's say, I can't meet my with customer today at 3 PM, hence I tried to update the time slot and they received notification that their meeting has been updated, but they did not receive a link to accept the change, decline it, or re-schedule it, however, at the end of the email it include a link to cancel the meeting, we don't want them to cancel the meeting.

3- Where would you change the content of  "Your appointment details have changed. Please review information below." ?

4- When creating new time slots, it always default to 8:30 AM spot, is there a way to adjust to default to 12 noon? Am trying to prevent human error as much as possible. 

Thank you Sergey for your awesome Plugin.

**Comment by SergeyMosin** [comment] 2024-01-26 17:43
Most of the work is going towards v2.0.0 release at this point, which will have most changes/improvements "under the hood" and in Settings UI. New features will be added in the later releases. 

- `#1` and `#3` are similar and would be in `Custom Email Templates` category ( duplicate of #470 )
- `#2` (rescheduling flow) is definitely something to consider is and will get implemented at some point
- `#4` probably will not  be implemented for while

At some point I will try to create a road map and prioritize some of the feature requests.

**Closed** 2024-07-28 21:21 UTC
Labels: duplicate
