### ISSUE TITLE
Confirmation Mail - Writing is striked out

### ISSUE THREAD

**Issue by stefan-franz** [SergeyMosin/Appointments#415] opened 2023-04-26 14:23 UTC
Here you see that some lines are striked out. What is the reason? 

![Appointments](https://user-images.githubusercontent.com/96744684/234605996-466e2c5f-1bb8-4a06-b77f-5f6c6c444042.jpg)

**Comment by stefan-franz** [comment] 2023-04-26 17:30
Now i see in Thunderbird, that its shown right....hmmmm....
That is a confirmed mail to the user who made the appointment via link. 


![Appointment - right](https://user-images.githubusercontent.com/96744684/234655320-1c149add-cc6d-4cef-bffc-8427cb292edf.jpg)

ics

BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//IDN nextcloud.com//Appointments App | srgdev.com//EN
CALSCALE:GREGORIAN
METHOD:PUBLISH
BEGIN:VTIMEZONE
TZID:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
SUMMARY:Stefan Franz Appointment
STATUS:CONFIRMED
TRANSP:OPAQUE
LAST-MODIFIED:20230426T141939Z
DTSTAMP:20230426T141913Z
SEQUENCE:3
CATEGORIES:Appointment
CREATED:20230426T141913Z
UID:1669aa5-1eb01b-a5924f-f3de78-tm754d7e2
DTSTART;TZID=Europe/Berlin:20230426T210000
DTEND;TZID=Europe/Berlin:20230426T213000
ORGANIZER;CN=Stefan Franz:mailto:office@stefan-franz.de
LOCATION:Zoom Kundenberatung / Customer Advice in DE/EN
ATTENDEE;CN=Stefan Franz 24;PARTSTAT=ACCEPTED:mailto:info@stefan-franz.de
DESCRIPTION:Stefan Franz\n+4917655186000\n
END:VEVENT
END:VCALENDAR

**Comment by SergeyMosin** [comment] 2023-04-26 17:56
I think Thunderbird is trying to show you changes. Because you get the first notification with the pending appointment and when the appointment is confirmed the title changes from the HourGlass icon to the new one.
The code for .ics files has nor been changed in while so I assume it is related to Thunderbird.

**Comment by SergeyMosin** [comment] 2023-07-02 13:48
Outside of this apps scope, closing.

**Closed by SergeyMosin** 2023-07-02 13:48 UTC
