### ISSUE TITLE
Not working with NC 25.0.5

### ISSUE THREAD

**Issue by Digitale-Substanz** [SergeyMosin/Appointments#408] opened 2023-03-24 14:41 UTC
Just updated to NC 25.0.5 (stable branch) and Appointments ist not working anymore.

Click on icon shows empty screen  (within the NC website framework). 

Should display administrator interface instead.

Could by reproduced on another NC instance. After update to 25.0.5 app not working anymore.

**Comment by SergeyMosin** [comment] 2023-03-24 16:54
@Digitale-Substanz This bug seems to be affecting some user but not others. I can not replicate it yet. Can you please send me (sergey [at] srgdev.com) your settings dump `Settings > Advanced Settings > Debugging > Settings Dump` so I can match your settings on my machine

Thank you.

**Comment by SergeyMosin** [comment] 2023-03-24 16:56
And if possible can you check logs and/or browser console for errors.
Thanks again

**Comment by filewalker1** [comment] 2023-03-24 17:07
Hi @SergeyMosin. Thank you for your great work!! Sadly i am experiencing the same issue. Tried with chrome and firefox, cleared chache,... still not there.
No error or warning in nextcloud log.
Error in browser console (i changed my domainname to "my.tld"):

`
Uncaught ReferenceError: process is not defined
    3585 https://myt.tld/apps/appointments/js/script.js?v=a8f5f4f1-0:2
    r https://my.tld/apps/appointments/js/script.js?v=a8f5f4f1-0:2
    6464 https://my.tld/apps/appointments/js/script.js?v=a8f5f4f1-0:2
    a https://my.tld/apps/appointments/js/script.js?v=a8f5f4f1-0:2
    5108 https://my.tld/apps/appointments/js/script.js?v=a8f5f4f1-0:2
    a https://my.tld/apps/appointments/js/script.js?v=a8f5f4f1-0:2
    8557 https://my.tld/apps/appointments/js/script.js?v=a8f5f4f1-0:2
    a https://my.tld/apps/appointments/js/script.js?v=a8f5f4f1-0:2
    8404 https://my.tld/apps/appointments/js/script.js?v=a8f5f4f1-0:2
    a https://my.tld/apps/appointments/js/script.js?v=a8f5f4f1-0:2
    7106 https://my.tld/apps/appointments/js/script.js?v=a8f5f4f1-0:2
    7106 https://my.tld/apps/appointments/js/script.js?v=a8f5f4f1-0:2
    7106 https://my.tld/apps/appointments/js/script.js?v=a8f5f4f1-0:2
    7106 https://my.tld/apps/appointments/js/script.js?v=a8f5f4f1-0:2
    7106 https://my.tld/apps/appointments/js/script.js?v=a8f5f4f1-0:2
    r https://my.tld/apps/appointments/js/script.js?v=a8f5f4f1-0:2
    <anonymous> https://my.tld/apps/appointments/js/script.js?v=a8f5f4f1-0:2
    <anonymous> https://my.tld/apps/appointments/js/script.js?v=a8f5f4f1-0:2
    <anonymous> https://my.tld/apps/appointments/js/script.js?v=a8f5f4f1-0:2
script.js:2:1871138
    3585 https://my.tld/apps/appointments/js/script.js?v=a8f5f4f1-0:2
    r https://my.tld/apps/appointments/js/script.js?v=a8f5f4f1-0:2
    6464 https://my.tld/apps/appointments/js/script.js?v=a8f5f4f1-0:2
    a https://my.tld/apps/appointments/js/script.js?v=a8f5f4f1-0:2
    5108 https://my.tld/apps/appointments/js/script.js?v=a8f5f4f1-0:2
    a https://my.tld/apps/appointments/js/script.js?v=a8f5f4f1-0:2
    8557 https://my.tld/apps/appointments/js/script.js?v=a8f5f4f1-0:2
    a https://my.tld/apps/appointments/js/script.js?v=a8f5f4f1-0:2
    8404 https://my.tld/apps/appointments/js/script.js?v=a8f5f4f1-0:2
    a https://my.tld/apps/appointments/js/script.js?v=a8f5f4f1-0:2
    7106 https://my.tld/apps/appointments/js/script.js?v=a8f5f4f1-0:2
    7106 https://my.tld/apps/appointments/js/script.js?v=a8f5f4f1-0:2
    7106 https://my.tld/apps/appointments/js/script.js?v=a8f5f4f1-0:2
    7106 https://my.tld/apps/appointments/js/script.js?v=a8f5f4f1-0:2
    7106 https://my.tld/apps/appointments/js/script.js?v=a8f5f4f1-0:2
    r https://my.tld/apps/appointments/js/script.js?v=a8f5f4f1-0:2
    <anonym> https://my.tld/apps/appointments/js/script.js?v=a8f5f4f1-0:2
    <anonym> https://my.tld/apps/appointments/js/script.js?v=a8f5f4f1-0:2
    <anonym> https://my.tld/apps/appointments/js/script.js?v=a8f5f4f1-0:2
`

**Comment by SergeyMosin** [comment] 2023-03-25 00:22
Linking to issue #406 , because I can replicate this on NC26.

**Comment by SergeyMosin** [comment] 2023-03-25 13:03
I can not verify that the error effecting NC25.0.5 is fixed, a very similar(possibly the same) error on NC26 is fixed in v1.14.12

**Comment by filewalker1** [comment] 2023-03-25 13:31
I do not know how the release process into nextcloud app store is handled, but i can only see your release on github, not in my nc instance or nc-store. as soon as i can update i will report back.

**Comment by filewalker1** [comment] 2023-03-25 18:46
> I can not verify that the error effecting NC25.0.5 is fixed, a very similar(possibly the same) error on NC26 is fixed in v1.14.12

Thank you so much for you quick reactions! I Just received the Update and i can confirm, it is working fine now ;)

**Closed** 2023-04-09 20:04 UTC
