### ISSUE TITLE
Public link could not be copied to clipboard...

### ISSUE THREAD

**Issue by cjk2** [SergeyMosin/Appointments#36] opened 2020-03-23 08:33 UTC
Hello, 
in my NextCloud installation I can unfortunately not use this app at all. I use NextCloud 18.0.2
If I try to copy the public link, I get the message "Public link could not be copied to clipboard...".
Even when I try to add an event, I don't get it displayed anywhere.
Any idea where I could look up?
Christian

**Comment by SergeyMosin** [comment] 2020-03-23 12:16
Can you add appointments via the "Add appointments" button ?
Does the "preview" form work ?  
Are there any error in the browser console or the log file ?

Thanks

**Comment by maesitopi** [comment] 2020-03-30 07:51
Hi @SergeyMosin ,

I am experiencing the same issue here. On my side it's only the "public link could not be copied to clipboard." Using nextcloud 18.0.3 in a docker environment. My Mail server is not configured yet.


**What Works:**
- The preview form works
- I can add appointments to the calendar
- If I use the preview form, the appointments are added to my calendar.

On my side, I get the following error in the console. However this also shows up on other pages and apps (probably the Proxy)

`Unrecognized Content-Security-Policy directive 'worker-src'.`

I could try to help track it down.

regards, malm

**Comment by SergeyMosin** [comment] 2020-03-30 13:17
Confirmed. Looks like Safari does not like vue-clipboard2.$copyText() However the public page it's self is not effect. This should be fixed in the next release.

Thanks.

**Comment by SergeyMosin** [comment] 2020-04-20 22:02
Fixed in v1.4.0

**Closed by SergeyMosin** 2020-04-20 22:02 UTC
