### ISSUE TITLE
[bug?] cant install app

### ISSUE THREAD

**Issue by OlafDammann** [SergeyMosin/Appointments#169] opened 2021-01-23 15:43 UTC
Hi there
Can't install the App. "occ app:install appointments" says:

Error: Undefined class constant 'INTEGER' in /var/www/mydomain/httpdocs/apps/appointments/lib/Migration/Version010201Date20200404181716.php:28
Stack trace:
#0 /var/www/mydomain/httpdocs/lib/private/DB/MigrationService.php(455): OCA\Appointments\Migration\Version010201Date20200404181716->changeSchema( )
#1 /var/www/mydomain/httpdocs/lib/private/DB/MigrationService.php(418): OC\DB\MigrationService->migrateSchemaOnly()
#2 /var/www/mydomain/httpdocs/lib/private/Installer.php(163): OC\DB\MigrationService->migrate()
#3 /var/www/mydomain/httpdocs/core/Command/App/Install.php(68): OC\Installer->installApp()
#4 /var/www/mydomain/httpdocs/apps/mail/vendor/symfony/console/Command/Command.php(255): OC\Core\Command\App\Install->execute()
#5 /var/www/mydomain/httpdocs/apps/mail/vendor/symfony/console/Application.php(971): Symfony\Component\Console\Command\Command->run()
#6 /var/www/mydomain/httpdocs/apps/mail/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand()
#7 /var/www/mydomain/httpdocs/apps/mail/vendor/symfony/console/Application.php(166): Symfony\Component\Console\Application->doRun()
#8 /var/www/mydomain/httpdocs/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#9 /var/www/mydomain/httpdocs/console.php(100): OC\Console\Application->run()
#10 /var/www/mydomain/httpdocs/occ(11): require_once('/var/www/office...')

Any ideas, what I do wrong?
Thank
OLAF

**Comment by SergeyMosin** [comment] 2021-01-23 20:13
This is very odd.
The error refers to line 28 which is:
```
  $table->addColumn('id', Type::INTEGER, [
```
and ``Type::INTEGER`` is defined in ``Doctrine\DBAL\Types\Type;``

Does the app install the 'usual way', from the 'Apps UI' ?

What version of NC are you using ?

 Do you have this file ``/var/www/mydomain/httpdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Types/Type.php`` ?

**Comment by SergeyMosin** [comment] 2021-01-23 20:28
Actually I see where the problem is. NC update the 'doctrine' to v3 a couple of weeks ago, and there some backwards compatibility issues. I'll push the fix.

**Comment by OlafDammann** [comment] 2021-01-24 15:48
cool, thanks for our quick response! I look forward.
You build this as "YouCanBook.me"-Replacement?

**Comment by SergeyMosin** [comment] 2021-02-24 12:23
This was fixed in 1.8.0

**Closed by SergeyMosin** 2021-02-24 12:23 UTC
